//
// Generated file, do not edit! Created by opp_msgc 4.1 from common/FiWiMessages.msg.
//

#ifndef _FIWIMESSAGES_M_H_
#define _FIWIMESSAGES_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>common/FiWiMessages.msg</tt> by opp_msgc.
 * <pre>
 * packet FiWiMessage
 * {
 *     string pktType;
 *     string host;
 *     int color;
 * }
 * </pre>
 */
class FiWiMessage : public ::cPacket
{
  protected:
    opp_string pktType_var;
    opp_string host_var;
    int color_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const FiWiMessage&);

  public:
    FiWiMessage(const char *name=NULL, int kind=0);
    FiWiMessage(const FiWiMessage& other);
    virtual ~FiWiMessage();
    FiWiMessage& operator=(const FiWiMessage& other);
    virtual FiWiMessage *dup() const {return new FiWiMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getPktType() const;
    virtual void setPktType(const char * pktType_var);
    virtual const char * getHost() const;
    virtual void setHost(const char * host_var);
    virtual int getColor() const;
    virtual void setColor(int color_var);
};

inline void doPacking(cCommBuffer *b, FiWiMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, FiWiMessage& obj) {obj.parsimUnpack(b);}


#endif // _FIWIMESSAGES_M_H_
